### ISSUE TITLE
Enable installation of the latest version if possible

### ISSUE THREAD

**Issue by yves-vogl** [yves-vogl/ansible-role-virtualbox-guest#1]
We can check if the host version of VirtualBox is compabtible with the latest version available by comparing the [semantic version numbers](http://semver.org).

```yaml
- name: Get the latest version of VirtualBox
  uri:
    url: http://download.virtualbox.org/virtualbox/LATEST.TXT
    return_content: yes        
  register: latest_virtualbox_version_request 
  
- name: Register latest version of VirtualBox
  set_fact:
   latest_virtualbox_version: "{{ latest_virtualbox_version_request.content | trim }}"      
 
- name: Check if latest version can be installed without incompatibilities
  set_fact: 
    install_latest_virtual_version: true
  when: semver.compare(host_virtualbox_version, latest_virtualbox_version)
```
